# .github/workflows/sync-fork.yml
name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight UTC
  workflow_dispatch: # also allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configure Git
        run: |
          git config --global user.email "tejveer.sf@gmail.com"
          git config --global user.name "Tejveer008"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/agupta890/Buyzone.git
          git fetch upstream
          git checkout main
          git merge upstream/main --allow-unrelated-histories
          git push origin main
